name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the version as needed

    - name: Install Tesseract OCR
      run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pytesseract pillow pandas PyMuPDF

    - name: Run Streamlit
      run: streamlit run app.py
